# DDNS配置文件示例
# 间隔时间（秒）
sleep_secs = 120
# 每隔几次强制从dnspod获取最新的记录
force_get_record_interval = 5

# 默认配置（可选）
default_token = "12345,xxxxxxxxxxxxxxxxxx"
default_ip_url = "https://www.arloor.com/ip"

# 域名配置列表
# 完整域名格式：
# - "sub.example.com" 表示子域名记录
# - "@.example.com" 或 "example.com" 表示根域名记录
[[domains]]
domain = "k3s.arloor.com"
# token = "可选，未设置时使用default_token"
# ip_url = "可选，未设置时使用default_ip_url"

# 第二个域名示例（根域名）
# [[domains]]
# domain = "@.example.com"  # 或者直接写 "example.com"
# token = "your_specific_token_here"
# ip_url = "https://api.ipify.org"
