name: Update

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build_musl
        id: build_musl
        uses: arloor/rust_musl_action@v2
      - name: gihub_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if $(gh release delete v1.0.0 -y --cleanup-tag); 
            then echo "delete old release"; 
            else echo "no old release";
          fi
          git config --local user.email "admin@arloor.com"
          git config --local user.name "arloor"
          git tag  -f v1.0.0 -m 'latest'
          git push --force origin v1.0.0
          gh release create v1.0.0 ${{ steps.build_musl.outputs.release_dir }}ddns --notes-from-tag --latest -t latest 